using Microsoft.EntityFrameworkCore;
using WeatherTeller.Persistence.EntityFramework.Settings;

namespace WeatherTeller.Persistence.EntityFramework;

internal class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
    {
    }
    
    public DbSet<SettingsEntity> Settings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SettingsEntity>().HasKey(x => x.Id);
        modelBuilder.Entity<SettingsEntity>().OwnsOne(x => x.Location);
        modelBuilder.Entity<SettingsEntity>().Property(x => x.ApiKey).IsRequired(false);
        // set autogenerated Ids
        
        base.OnModelCreating(modelBuilder);
    }
}